name: Build and Push Multiarch Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub (for caching)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ghcr.io/jakubgoreckii/lab11-multiarch-ci:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=goras1234/cache:lab11
          cache-to: type=registry,ref=goras1234/cache:lab11,mode=max
          outputs: type=docker,dest=image.tar

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: image.tar
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Push image to GHCR if no CVEs
        if: success()
        run: |
          docker load -i image.tar
          docker push ghcr.io/jakubgoreckii/lab11-multiarch-ci:latest
